name: Deploy Chat API

on: 
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvc6p6rqf0us73dd58v0?key=${{ secrets.RENDER_DEPLOY_KEY }}"
